const CARS_REQUEST = 'CARS_REQUEST';
const CARS_SUCCESS = 'CARS_SUCCESS';
const CARS_ERROR = 'CARS_ERROR';
const WINNERS_REQUEST = 'WINNERS_REQUEST';
const WINNERS_SUCCESS = 'WINNERS_SUCCESS';
const WINNERS_ERROR = 'WINNERS_ERROR';
const PAGE_CHANGED = 'PAGE_CHANGED';
const GARAGE_PAGE_NUMBER_CHANGED = 'GARAGE_PAGE_NUMBER_CHANGED';
const WINNER_PAGE_NUMBER_CHANGED = 'WINNER_PAGE_NUMBER_CHANGED';
const CAR_CREATED = 'CAR_CREATED';
const NEW_CAR_COLOR_CHANGED = 'NEW_CAR_COLOR_CHANGED';
const NEW_CAR_NAME_CHANGED = 'NEW_CAR_NAME_CHANGED';
const SELECTED_CAR_COLOR_CHANGED = 'SELECTED_CAR_COLOR_CHANGED';
const SELECTED_CAR_NAME_CHANGED = 'SELECTED_CAR_NAME_CHANGED';
const CAR_DELETED = 'CAR_DELETED';
const CAR_DELETE_FAILED = 'CAR_DELETE_FAILED';
const CAR_SELECTED = 'CAR_SELECTED';
const CAR_UPTADED = 'CAR_UPTADED';
const CAR_UPTADE_FAILED = 'CAR_UPTADE_FAILED';
const CAR_ENGINE_STARTED_REQUEST = 'CAR_ENGINE_STARTED_REQUEST';
const CAR_ENGINE_STARTED_SUCCESS = 'CAR_ENGINE_STARTED_SUCCESS';
const CAR_ENGINE_STARTED_ERROR = 'CAR_ENGINE_STARTED_ERROR';
const CAR_ENGINE_STOPPED_REQUEST = 'CAR_ENGINE_STOPPED_REQUEST';
const CAR_ENGINE_STOPPED_SUCCESS = 'CAR_ENGINE_STOPPED_SUCCESS';
const CAR_ENGINE_STOPPED_ERROR = 'CAR_ENGINE_STOPPED_ERROR';
const WINNER_CREATED = 'WINNER_CREATED';
const CAR_WON = 'CAR_WON';
const SORT_DIRECTION_CHANGED = 'SORT_DIRECTION_CHANGED';

export {
  CARS_REQUEST,
  CARS_SUCCESS,
  CARS_ERROR,
  PAGE_CHANGED,
  WINNERS_REQUEST,
  WINNERS_SUCCESS,
  WINNERS_ERROR,
  CAR_CREATED,
  NEW_CAR_COLOR_CHANGED,
  NEW_CAR_NAME_CHANGED,
  CAR_DELETED,
  CAR_DELETE_FAILED,
  CAR_SELECTED,
  SELECTED_CAR_COLOR_CHANGED,
  SELECTED_CAR_NAME_CHANGED,
  CAR_UPTADED,
  CAR_UPTADE_FAILED,
  GARAGE_PAGE_NUMBER_CHANGED,
  CAR_ENGINE_STARTED_REQUEST,
  CAR_ENGINE_STARTED_SUCCESS,
  CAR_ENGINE_STARTED_ERROR,
  CAR_ENGINE_STOPPED_REQUEST,
  CAR_ENGINE_STOPPED_SUCCESS,
  CAR_ENGINE_STOPPED_ERROR,
  WINNER_CREATED,
  WINNER_PAGE_NUMBER_CHANGED,
  CAR_WON,
  SORT_DIRECTION_CHANGED,
};
