const CARS_REQUEST = 'CARS_REQUEST';
const CARS_SUCCESS = 'CARS_SUCCESS';
const CARS_ERROR = 'CARS_ERROR';
const PAGE_CHANGED = 'PAGE_CHANGED';

export { CARS_REQUEST, CARS_SUCCESS, CARS_ERROR, PAGE_CHANGED };
