const CARS_REQUEST = 'CARS_REQUEST';
const CARS_SUCCESS = 'CARS_SUCCESS';
const CARS_ERROR = 'CARS_ERROR';
const WINNERS_REQUEST = 'WINNERS_REQUEST';
const WINNERS_SUCCESS = 'WINNERS_SUCCESS';
const WINNERS_ERROR = 'WINNERS_ERROR';
const PAGE_CHANGED = 'PAGE_CHANGED';
const PAGE_NUMBER_CHANGED = 'PAGE_NUMBER_CHANGED';
const CAR_CREATED = 'CAR_CREATED';
const NEW_CAR_COLOR_CHANGED = 'NEW_CAR_COLOR_CHANGED';
const NEW_CAR_NAME_CHANGED = 'NEW_CAR_NAME_CHANGED';
const SELECTED_CAR_COLOR_CHANGED = 'SELECTED_CAR_COLOR_CHANGED';
const SELECTED_CAR_NAME_CHANGED = 'SELECTED_CAR_NAME_CHANGED';
const CAR_DELETED = 'CAR_DELETED';
const CAR_SELECTED = 'CAR_SELECTED';
const CAR_UPTADED = 'CAR_UPTADED';

export {
  CARS_REQUEST,
  CARS_SUCCESS,
  CARS_ERROR,
  PAGE_CHANGED,
  WINNERS_REQUEST,
  WINNERS_SUCCESS,
  WINNERS_ERROR,
  CAR_CREATED,
  NEW_CAR_COLOR_CHANGED,
  NEW_CAR_NAME_CHANGED,
  CAR_DELETED,
  CAR_SELECTED,
  SELECTED_CAR_COLOR_CHANGED,
  SELECTED_CAR_NAME_CHANGED,
  CAR_UPTADED,
  PAGE_NUMBER_CHANGED,
};
