const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';
const SWITCH_VALUE_CHANGED = 'SWITCH_VALUE_CHANGED';
const MENU_OPEN = 'MENU_OPEN';
const SET_CATEGORY = 'SET_CATEGORY';
const SET_GAME_START = 'SET_GAME_START';
const SET_AUDIOS = 'SET_AUDIOS';
const SET_PLAYED_AUDIO = 'SET_PLAYED_AUDIO';
const SET_CIRCLE = 'SET_CIRCLE';
const GAME_FINISHED = 'GAME_FINISHED';

export {
  SWITCH_VALUE_CHANGED,
  FETCH_CATEGORIES_REQUEST,
  FETCH_CATEGORIES_SUCCESS,
  FETCH_CATEGORIES_FAIL,
  MENU_OPEN,
  SET_CATEGORY,
  SET_GAME_START,
  SET_AUDIOS,
  SET_PLAYED_AUDIO,
  SET_CIRCLE,
  GAME_FINISHED,
};
