const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';
const SWITCH_VALUE_CHANGED = 'SWITCH_VALUE_CHANGED';
const MENU_OPEN = 'MENU_OPEN';
const SET_CATEGORY = 'SET_CATEGORY';

export {
  SWITCH_VALUE_CHANGED,
  FETCH_CATEGORIES_REQUEST,
  FETCH_CATEGORIES_SUCCESS,
  FETCH_CATEGORIES_FAIL,
  MENU_OPEN,
  SET_CATEGORY,
};
