const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';
const SWITCH_ITEM_CHANGED = 'SWITCH_ITEM_CHANGED';

export {
  SWITCH_ITEM_CHANGED,
  FETCH_CATEGORIES_REQUEST,
  FETCH_CATEGORIES_SUCCESS,
  FETCH_CATEGORIES_FAIL,
};
